wandb_version: 1

lr:
  desc: null
  value: 0.001
weight_decay:
  desc: null
  value: 0.0
optim_type:
  desc: null
  value: Adam
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693824478.663426
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.4
      5: 0.15.9
      8:
      - 5
